import Head from "next/head";
import {
  Paper,
  Typography,
  Box,
  Stack,
  Button,
} from "@mui/material";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Paper sx={{ padding: 20 }}>
          <Typography variant="h1">Loan Example</Typography>
          <Typography variant="subtitle1" paragraph noWrap={false}>
            Basic example that runs the user through a loan request. The user
            will be asked to fill out a form and then the loan will be approved
            or denied.
          </Typography>
          <Box mt={3} sx={{display:"flex",alignItems:"center",justifyContent:"center"}}>
            <Stack direction="row" spacing={2}>
              <Box>
                <Button
                  variant="contained"
                  color="primary"
                  href="/loan"
                  size="medium"
                >
                  Start/Continue Loan Request
                </Button>
              </Box>
              <Box>
                <Button
                  variant="contained"
                  color="primary"
                  href="/admin"
                  size="medium"
                >
                  Approve Reject Loans
                </Button>
              </Box>

            </Stack>
          </Box>
        </Paper>
      </main>
    </>
  );
}
